// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKUpwqe7a4PyG_4e2v6WnQ3HJT4Rt_0g',
    appId: '1:308068199132:web:c62b6cdb30556d0323e219',
    messagingSenderId: '308068199132',
    projectId: 'instagram-clone-84f28',
    authDomain: 'instagram-clone-84f28.firebaseapp.com',
    storageBucket: 'instagram-clone-84f28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcxGVs2pOxlQWPtEpGxPCbY2PHd8UKHW8',
    appId: '1:308068199132:android:9d673475cb42dd5123e219',
    messagingSenderId: '308068199132',
    projectId: 'instagram-clone-84f28',
    storageBucket: 'instagram-clone-84f28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAkMvIUPnJssp9LA1rpdwxnMpTInStT84',
    appId: '1:308068199132:ios:55dfdcf91714b51e23e219',
    messagingSenderId: '308068199132',
    projectId: 'instagram-clone-84f28',
    storageBucket: 'instagram-clone-84f28.appspot.com',
    iosClientId: '308068199132-nbhhcc2jicsun87gk5uu05586tof8e8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
